name: Build and Test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.1
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y sqlite3 libsqlite3-dev ninja-build libgtk-3-dev libglu1-mesa xvfb

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build
        run: make build-linux

      - name: Unit Test
        run: make test

      - name: Integration Test
        run: xvfb-run flutter test ./integration_test/main.dart -r github

